/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [24.2MB] > C:\Users\jonti\OneDrive\Desktop\web_remaster\web-portfolio-joe-v2\public\models\scenev1\scene-transformed.glb [2.6MB] (89%)
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function ModelMain(props) {
  const { nodes, materials } = useGLTF('/models/scenev1/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={5} decay={2} color="#5d5e4a" position={[-3.095, 2.475, 0.54]} />
      <pointLight intensity={0.24} decay={2} color="#348d54" position={[-0.284, 1.669, -1.08]} scale={[0.024, 0.023, 0.039]} />
      <pointLight intensity={2} decay={2} color="#382357" position={[0.909, 2.202, 0.971]} scale={[0.163, 0.328, 0.319]} />
      <PerspectiveCamera makeDefault={false} fov={84} position={[-0.38, 1.757, -0.58]} rotation={[0.098, 0.154, 0.084]} />
      <pointLight intensity={0.25} decay={2} color="#2939b3" position={[0.158, 1.492, -0.804]} rotation={[-Math.PI, 0, 0]} scale={[-0.069, 0.057, 0.071]} />
      <pointLight intensity={0.15} decay={2} color="#37d317" position={[0.755, 1.643, -0.737]} scale={[0.057, 0.146, 0.054]} />
      <pointLight intensity={1} decay={2} color="#feec7c" position={[0.004, 2.657, 0.013]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.note_1} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_1.geometry} material={materials['Plastic White 13']} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_2.geometry} material={materials['Plastic Black 3']} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_3.geometry} material={materials.PaletteMaterial002} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_4.geometry} material={materials.PaletteMaterial003} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_5.geometry} material={materials['Golden metal']} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_6.geometry} material={materials.ComputerCase} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_7.geometry} material={materials['09_-_Default']} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_8.geometry} material={materials['Material.001']} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_9.geometry} material={materials['Material.002']} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_10.geometry} material={materials.standing_picture_frame_01_artwork} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_11.geometry} material={materials['Dark iron']} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_12.geometry} material={materials.Speaker_mat} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_13.geometry} material={materials.flag_colorado} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_14.geometry} material={materials.DUBANNER_MAT} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_15.geometry} material={materials.PaletteMaterial001} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane003_16.geometry} material={materials.standing_picture_frame_01_glass} position={[-0.098, 1.84, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
    </group>
  )
}

useGLTF.preload('/models/scenev1/scene-transformed.glb')
