/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 webdev_site_3denv.gltf --transform 
Files: webdev_site_3denv.gltf [110.19KB] > C:\Users\jonti\OneDrive\Desktop\web_remaster\web-portfolio-joe-v2\public\models\scene\webdev_site_3denv-transformed.glb [2.79MB] (-2429%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/webdev_site_3denv-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.note_1} position={[-0.098, 1.413, -1.288]} rotation={[1.2, 0, 0]} scale={[0.05, 0.057, 0.052]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.flag_colorado} position={[-0.936, 1.992, -1.801]} rotation={[1.55, 0, 0]} scale={[0.626, 0.749, 0.375]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.DUBANNER_MAT} position={[0.118, 2.055, -1.803]} rotation={[-Math.PI / 2, -0.109, 0]} scale={[0.244, 0.304, 0.304]} />
      <mesh geometry={nodes.screen_plate.geometry} material={materials.PaletteMaterial001} position={[-0.284, 1.243, -1.284]} rotation={[1.403, 0, 0]} scale={[0.203, 0.193, 0.193]} />
      <mesh geometry={nodes.Office_table.geometry} material={materials.PaletteMaterial004} />
      <mesh geometry={nodes.Gigabyte_Computer.geometry} material={materials.ComputerCase} position={[0.222, 0.911, -1.205]} rotation={[0, -0.112, 0]} />
      <mesh geometry={nodes.Apple_Macintosh_keyboard.geometry} material={materials['Material.001']} position={[-0.259, 0.913, -1.115]} rotation={[0, -0.048, 0]} scale={1.232} />
      <mesh geometry={nodes.Office_Desk.geometry} material={materials['Dark iron']} position={[0.086, -0.112, -1.299]} scale={[1.19, 1.344, 1.34]} />
      <mesh geometry={nodes.BézierCurve.geometry} material={nodes.BézierCurve.material} />
      <mesh geometry={nodes['et_09_-_Default_0'].geometry} material={materials['09_-_Default']} position={[-0.283, 1.142, -1.454]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.002']} position={[-0.44, 0.979, -1.177]} rotation={[0.198, -0.047, 0.009]} scale={1.232} />
      <group position={[-0.667, 0.928, -1.362]} rotation={[0, 0.372, 0]} scale={0.969}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.standing_picture_frame_01_artwork} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials.standing_picture_frame_01_glass} />
      </group>
      <mesh geometry={nodes.Speaker.geometry} material={materials.Speaker_mat} position={[0.465, 0.919, -1.031]} rotation={[0, -0.881, 0]} scale={1.599} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Plastic White 13']} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials['Plastic Black 3']} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Cube001_3.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Cube001_4.geometry} material={materials['Golden metal']} />
    </group>
  )
}

useGLTF.preload('/webdev_site_3denv-transformed.glb')
